### Register Workshop Owner

###GET http://localhost:3232



### Register Magazine Owner with Referral
POST http://localhost:3232/api/auth/register/user
Content-Type: application/json

{
  "username": "magazineUser",
  "password": "password123",
  "email": "mag@example.com",
  "firstname": "Fatima",
  "lastname": "Ali",
  "phone": "0987654321",
  "userType": "MAGAZINE_OWNER",
  "referralCode": "abc123def456"
}


